version: "3.9"
services: 
  web:
    build: . 
    container_name: php_apache
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_DATABASE: cdweb
      MYSQL_USER: chandrabhan
      MYSQL_PASSWORD: chandrabhan
    ports:
      - 6033:3306       
